services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: -c 'sleep infinity'
    entrypoint: /bin/bash
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-..}:/usr/src/app:cached
